Suppose the IQ in a certain population is normally distributed with a mean of 100 and standard deviation od 15. A researcher wants to know if a new drug affects IQ levels, so he recruits 20 patients to try it and records their IQ levels. The following code shows how to perform a one sample z-test in python to determine if the new drig causes a significant difference in IQ levels.

In [1]:
from statsmodels.stats.weightstats import ztest as ztest

data = [88,92,94,96,97,97,99,99,105,109,110,112,112,113,114,115]

z_test = ztest(data,value=100)
z_test
print("Here ztest is: {} and p-value is: {}".format(z_test[0],z_test[1]))
print()
print()
if (z_test[1]<0.05):
    print("reject the null hypothesis")
else:
    print("accept the null hypothesis")

Here ztest is: 1.4564816895978787 and p-value is: 0.14525950774328536


accept the null hypothesis


# t-test

In [2]:
ages = [10,20,35,50,28,40,55,18,16,55,30,25,43,18,30,28,14,24,16,17,32,35,26,27,65,18,43,23,21,320,19,70]

In [3]:
import numpy as np
ages_mean = np.mean(ages)
ages_mean

39.71875

In [6]:
sample_size =10
age_sample=np.random.choice(ages,sample_size)

In [8]:
age_sample

array([ 16,  25,  70,  28,  26,  32,  40, 320,  28,  20])

In [11]:
np.mean(age_sample)

60.5

In [9]:
from scipy.stats import ttest_1samp

In [10]:
ttest_1samp(age_sample,30)

Ttest_1sampResult(statistic=1.0437801849180663, pvalue=0.3238113861600091)

consider anather example
ages of the college students(population)
1 class student mean of the all ages

In [14]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import math
np.random.seed(6)
school_ages=stats.poisson.rvs(loc=18,mu=35,size=1500)
classA_ages=stats.poisson.rvs(loc=18,mu=30,size=60)

In [15]:
school_ages

array([62, 59, 44, ..., 45, 52, 50])

In [16]:
classA_ages

array([52, 46, 40, 40, 47, 50, 51, 45, 44, 52, 46, 53, 43, 44, 51, 50, 54,
       42, 54, 45, 61, 53, 49, 46, 47, 41, 45, 51, 43, 45, 48, 50, 40, 52,
       44, 55, 54, 40, 45, 46, 54, 42, 46, 35, 51, 51, 46, 48, 47, 35, 52,
       52, 39, 44, 48, 40, 42, 46, 47, 45])

In [17]:
classA_ages.mean()

46.9

In [22]:
_,p_value=ttest_1samp(classA_ages,school_ages.mean())
p_value

1.139027071016194e-13

In [21]:
if p_value<0.05:
    print("Reject the null hypothesis")
else:
    print("accept the null hypothesis")

Reject the null hypothesis


In [23]:
import seaborn as sns

In [24]:
df = sns.load_dataset('iris')

URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

In [ ]:
df.corr()

In [ ]:
sns.pairplot(df)